name: Build And Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Login ToDockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build And Push
        uses: docker/build-push-action@v2
        with:
          context: ./app
          file: python3.8.dockerfile
          push: true
          tags: liuranlzz/pdfupload:one.${{ github.run_id }}.${{ github.run_number }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo "Sic Mundus Creatus Est"
            docker pull liuranlzz/pdfupload:one.${{ github.run_id }}.${{ github.run_number }}
            docker stop pdfupload-server
            docker rm pdfupload-server
            docker run -e COS_SECRET_ID=${{ secrets.FLASK_COS_SECRET_ID }} -e COS_SECRET_KEY=${{ secrets.FLASK_COS_SECRET_KEY }} -e SQL_URI=${{ secrets.FLASK_SQL_URI }} -p 9530:80 -d --name pdfupload-server  liuranlzz/pdfupload:one.${{ github.run_id }}.${{ github.run_number }}
            echo "GO!"



